// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr4RvvRIZJ41Ia5aUb9ab6GEzINiDUVT8',
    appId: '1:911981193074:web:aef7afa915441c95585feb',
    messagingSenderId: '911981193074',
    projectId: 'easacc-52e5e',
    authDomain: 'easacc-52e5e.firebaseapp.com',
    storageBucket: 'easacc-52e5e.firebasestorage.app',
    measurementId: 'G-WNS6CDH04R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACA75ms9hjbUW-wOtmeFKiJr_crc120g0',
    appId: '1:911981193074:android:ca97b3fb0bde1e75585feb',
    messagingSenderId: '911981193074',
    projectId: 'easacc-52e5e',
    storageBucket: 'easacc-52e5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDZYR0vUinxiqXVHo-dMl5B4qvQ_nsHog',
    appId: '1:911981193074:ios:301fdc00da28275f585feb',
    messagingSenderId: '911981193074',
    projectId: 'easacc-52e5e',
    storageBucket: 'easacc-52e5e.firebasestorage.app',
    iosClientId: '911981193074-j2oner5g91bujundl42kd15b1b71cebi.apps.googleusercontent.com',
    iosBundleId: 'com.example.easacc',
  );
}
